trigger:
  - main

pool: default

steps:
  - task: UseNode@1
    inputs:
      version: '16.x'
    displayName: 'Install Node.js'

  - checkout: self
    persistCredentials: true

  - script: |
      ls -lath
      pwd
      cd $(Build.SourcesDirectory)
      ls -la   # List the files in the directory for debugging
      npm install
    displayName: 'npm install'

  - script: |
      cd $(Build.SourcesDirectory)
      npm run build
    displayName: 'npm build'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
        src/*
        public/*
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy project files'

  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: 'e2e-server'
      targetPath: '$(Build.ArtifactStagingDirectory)'
      publishLocation: 'pipeline'
    displayName: 'Publish npm artifact'
