# Node.js
# Build and deploy a React.js project with npm.
# For more information, visit: https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/build'
    artifactName: 'build'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'

# Additional steps for code analysis, testing, deployment, etc. can be added here
